<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.wixproj'">
    <BaseIntermediateOutputPath>obj\wix\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj\wix\</MSBuildProjectExtensionsPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetLockFilePath>packages.wix.lock.json</NuGetLockFilePath>
  </PropertyGroup>
</Project>
