<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="[2.7.0]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hch.Worker.Protocol\Hch.Worker.Protocol.csproj" />
  </ItemGroup>

</Project>
